import type { Metadata } from "next";
import { Libre_Baskerville, Lora, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";

const libreBaskerville = Libre_Baskerville({
  variable: "--font-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const lora = Lora({
  variable: "--font-serif",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libreBaskerville.variable} ${lora.variable} ${ibmPlexMono.variable} antialiased`}>
        <div className="h-screen w-full relative">
          {/* Background image */}
          <div 
            className="absolute inset-0 bg-cover bg-center bg-no-repeat"
            style={{
              backgroundImage: 'url(/background.jpg)'
            }}
          />
          {/* Overlay depends on theme: dark = black/30, light = white/70 */}
          <div className="absolute inset-0 dark:bg-black/30 bg-white/70" />
          {/* TopBar */}
          <TopBar />
          {/* Content */}
          <div className="electron-no-drag relative min-h-[calc(100vh-24px)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
